// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/5/2026, 11:17:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/itmzt002/Documents/Projects/POS/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/plugins/**/*.{js,ts,mjs}","/Users/itmzt002/Documents/Projects/POS/frontend/composables/**/*.{js,ts,mjs}","/Users/itmzt002/Documents/Projects/POS/frontend/utils/**/*.{js,ts,mjs}","/Users/itmzt002/Documents/Projects/POS/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/itmzt002/Documents/Projects/POS/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;